package com.tourpackage.api.entity;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "bookings")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Booking {

    @Id
    @GeneratedValue
    private UUID id;

    /**
     * Generated by the column's DB default ({@code 'TP-' || year || sequence}),
     * not by the application — a sequence is atomic under concurrent inserts in
     * a way that "read the last number and add one" isn't. {@code insertable =
     * false} keeps Hibernate from overwriting the default with a null, and
     * {@link Generated} makes it read the value back after the INSERT.
     */
    @Generated(event = EventType.INSERT)
    @Column(name = "booking_number", nullable = false, updatable = false, insertable = false, length = 30)
    private String bookingNumber;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Enumerated(EnumType.STRING)
    @Column(name = "booking_type", nullable = false, length = 10)
    private BookingType bookingType;

    @Column(name = "package_id")
    private UUID packageId;

    @Column(name = "hotel_room_id")
    private UUID hotelRoomId;

    @Column(name = "travel_date", nullable = false)
    private LocalDate travelDate;

    @Column(name = "return_date")
    private LocalDate returnDate;

    @Column(name = "number_of_adults", nullable = false)
    private short numberOfAdults;

    @Column(name = "number_of_children", nullable = false)
    private short numberOfChildren;

    @Column(name = "total_amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal totalAmount;

    @Column(name = "currency_code", nullable = false, length = 3)
    private String currencyCode;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private BookingStatus status;

    @Column(name = "special_requests")
    private String specialRequests;

    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    @Column(name = "cancellation_reason", length = 500)
    private String cancellationReason;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

}
