package com.tourpackage.api.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.tourpackage.api.dto.response.ApiResponse;
import com.tourpackage.api.dto.response.SitemapResponse;
import com.tourpackage.api.repository.BlogPostRepository;
import com.tourpackage.api.repository.HotelRepository;
import com.tourpackage.api.repository.TourPackageRepository;

/**
 * Data the frontend needs to build {@code sitemap.xml}.
 *
 * <p>The XML itself is generated by Next.js, which is the only side that knows
 * the site's route structure — that a hotel lives at {@code /hotels/{slug}} is a
 * frontend fact, not a backend one. This endpoint supplies only what the
 * database knows: which entities are publicly visible, and when each changed.
 */
@RestController
@RequestMapping("/public/seo")
public class SeoController {

    private final HotelRepository hotelRepository;
    private final TourPackageRepository tourPackageRepository;
    private final BlogPostRepository blogPostRepository;

    public SeoController(
            HotelRepository hotelRepository,
            TourPackageRepository tourPackageRepository,
            BlogPostRepository blogPostRepository) {
        this.hotelRepository = hotelRepository;
        this.tourPackageRepository = tourPackageRepository;
        this.blogPostRepository = blogPostRepository;
    }

    @GetMapping("/sitemap")
    public ApiResponse<SitemapResponse> sitemap() {
        return ApiResponse.of(new SitemapResponse(
                hotelRepository.findSitemapEntries(),
                tourPackageRepository.findSitemapEntries(),
                blogPostRepository.findSitemapEntries()));
    }

}
